#ifndef HAVE_PROTOCOL_DEFINES
#define HAVE_PROTOCOL_DEFINES

#define SYS_PANTILT 0x01
#define SYS_CAMERA 0x02
#define SYS_BAROMETER 0x03
#define SYS_ACCEL 0x04
#define SYS_PING 0x05

#define PANTILT_MOVE 0x01
#define PANTILT_MOVEALL 0x03
#define PANTILT_COMPLIANCE 0x02

#define BAROMETER_DATA 0x01
#define BAROMETER_CALIB1 0x02
#define BAROMETER_CALIB2 0x03

#define ACCEL_AVERAGE 0x01
#define ACCEL_CURRENT 0x02

#define CAMERA_ZOOM 0x01
#define CAMERA_COMMAND 0x02

#endif
